# importing numpy

In [1]:
import numpy as np

# arange()

In [5]:
#np.arange(start,end,step)
ar_1d=np.arange(1,10)
print(ar_1d)

[1 2 3 4 5 6 7 8 9]


# linspace(start,end,how many points you want in between)

In [6]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

# creating data 

In [9]:
np.array([[1,1,1],[1,1,1],[1,1,1]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
arr=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
arr1=np.arange(1,9)
print(arr1)

[1 2 3 4 5 6 7 8]



# reshape

In [13]:
arr.reshape(9)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
arr.reshape(1,3,3)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [37]:
arr1a=arr1.reshape(4,2)
print(arr1a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# ravel()

In [33]:
arr1=arr.ravel()
print(arr1)

[1 1 1 1 1 1 1 1 1]


In [38]:
arr1a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

# transpose()

In [27]:
arr1.transpose()

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [39]:
arr1b=arr1a.T
print(arr1b)

[[1 3 5 7]
 [2 4 6 8]]
