In [2]:
import numpy as np

In [9]:
arrA0=np.arange(1,10,dtype=int).reshape(3,3)
arrB0=np.arange(10,19,dtype=int).reshape(3,3)
print(arrA0)
print(arrB0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


# ADD

In [10]:
 arrB0 +arrA0

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [11]:
np.add(arrB0,arrA0)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

# sub

In [12]:
arrA0-arrB0

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [14]:
np.subtract(arrB0,arrA0)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# DIVIDE

In [15]:
np.divide(arrA0,arrB0)

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [16]:
arrA0/arrB0

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

# Element vice multiplication

In [17]:
arrA0*arrB0

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [18]:
np.multiply(arrA0,arrB0)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

# Matrix multiplication

In [19]:
arrA0@arrB0

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [21]:
arrA0.dot(arrB0)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

# Find maximum

In [22]:
arrA0.max()

9

# Finding the maximum value index

In [23]:
arrA0.argmax()

8

# Maxmium value of column

In [25]:
arrB0.max(axis=0)

array([16, 17, 18])

# Maxmium value of row wise

In [26]:
arrB0.max(axis=1)

array([12, 15, 18])

# Minimium value of row wise

In [29]:
arrA0.min(axis=1)

array([1, 4, 7])

# Minimium value of column  wise

In [31]:
arrA0.min(axis=0)

array([1, 2, 3])

# Finding the minimum value index

In [33]:
arrB0.argmin()

0

# sum of each value of matrix

In [34]:
np.sum(arrA0)

45

# sum of each column wise  values of matrix

In [35]:
np.sum(arrA0,axis=0)

array([12, 15, 18])

# sum of each values row wise values of matrix

In [36]:
np.sum(arrA0,axis=1)

array([ 6, 15, 24])

# mean of  values of matrix

In [38]:
np.mean(arrB0)

14.0

# square root of each value of matrix

In [40]:
np.sqrt(arrB0)

array([[3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069]])

# Standart division root of each value of matrix

In [42]:
np.std(arrB0)

2.581988897471611

# exponent root of each value of matrix

In [43]:
np.exp(arrB0)

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]])

# log  of each value of matrix

In [44]:
np.log(arrB0)

array([[2.30258509, 2.39789527, 2.48490665],
       [2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176]])