# python Numpy Array slicing 


In [2]:
import numpy as np

In [26]:
mx=np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [28]:
#mx[row start:row end,col start: col end] # if yo not giving end value then 1d
mx[0]# zero for scalar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#mx[row start:row end,col start: col end] # if yo not giving end value then 1d
mx[:,0] #for first col in row form , 1Dim

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [21]:
#mx[row start:row end,col start: col end]
mx[0:6] #for first col in col form ,2 Dim

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [23]:
#mx[row start:row end,col start: col end]
mx[:,1:6]# zero for scalar #for first col in col form ,2 Dim

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56],
       [62, 63, 64, 65, 66],
       [72, 73, 74, 75, 76],
       [82, 83, 84, 85, 86],
       [92, 93, 94, 95, 96]])

In [16]:
#mx[row start:row end,col start: col end]
mx[2:5,3:6]

array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])

In [17]:
#mx[row start:row end,col start: col end]
mx[2:5,2:6]

array([[23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46]])