In [1]:
import numpy as np
import random 

# random

In [2]:
#np.module.function(int for 1 element)
#random for less then 1 value
np.random.random(1)

array([0.01366557])

In [3]:
#np.module.function(tuple for matrix)
#random for less then 1 value
np.random.random((3,3))

array([[0.54773275, 0.46640787, 0.3867984 ],
       [0.4162412 , 0.76938225, 0.68034222],
       [0.54147419, 0.45318388, 0.92627073]])

# randint

In [4]:
#np.module.function(range start ,range end ,size tuple  for matrix)
#randint for integer value
np.random.randint(1,4)

3

In [5]:
# np.module.function(range start ,range end ,size tuple  for matrix)
#randint for integer value
np.random.randint(1,5,(3,3))

array([[1, 3, 4],
       [2, 4, 4],
       [1, 4, 3]])

# rand

In [6]:
#rand for get array of  values less then 1
#np.module.function(num of ele in array)
np.random.rand(4)

array([0.03609826, 0.49887914, 0.94523836, 0.87032384])

In [7]:
#rand for get array of  values less then 1
#np.module.function(num of ele in row,num of ele in col)
np.random.rand(4,2)

array([[0.58335064, 0.93755983],
       [0.73341551, 0.60134908],
       [0.27050368, 0.00893733],
       [0.70089534, 0.13862946]])

# choice

In [8]:
from_this=[32,2324,234234,23423,23424]
np.random.choice(from_this)

23424